raise Exception("This is a manually raised exception!")
